stages:
  - publish

before_script:
  - echo "${CI_REGISTRY}"
  - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish:
  stage: publish
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags:
    - docker
  script:
    - echo "${CI_REGISTRY_IMAGE}"
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest docker
    - docker push $CI_REGISTRY_IMAGE:latest
