stages:
  - publish
  - deploy

before_script:
  - sudo -n docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish_inside:
  stage: publish
  tags:
    - shell
  script:
    - sudo docker build --pull -t $CI_REGISTRY_IMAGE/inside:latest inside
    - sudo docker push $CI_REGISTRY_IMAGE/inside:latest
  only:
    - master

publish_outside:
  stage: publish
  tags:
    - tokyo, vpn
  script:
    - sudo docker build --pull -t $CI_REGISTRY_IMAGE/outside:latest outside
    - sudo docker push $CI_REGISTRY_IMAGE/outside:latest
  only:
    - master


deploy_inside:
  stage: deploy
  tags:
    - shell
    - gitlab
  script:
    - ./deploy_inside.sh
  only:
    - master

deploy_outside:
  stage: deploy
  tags:
    - shell
    - tokyo
  script:
    - ./deploy_outside.sh
  only:
    - master
