stages:
  - publish

before_script:
  - echo "${CI_REGISTRY}"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish:
  stage: publish
  tags:
    - shell
  script:
    - echo "${CI_REGISTRY_IMAGE}"
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest docker
    - docker push $CI_REGISTRY_IMAGE:latest
