stages:
  - publish
  - deploy

before_script:
  - sudo -n docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish:
  stage: publish
  tags:
    - shell
  script:
    - sudo docker build --pull -t $CI_REGISTRY_IMAGE:latest docker
    - sudo docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy_hk:
  stage: deploy
  tags:
    - shell
    - vpn-hk
  script:
    - ./deploy.sh
  only:
    - master

deploy_tw:
  stage: deploy
  tags:
    - shell
    - vpn-tw
  script:
    - ./deploy.sh
  only:
    - master
