stages:
  - publish

before_script:
  - echo "${CI_REGISTRY}"
  - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

publish:
  stage: publish
  tags:
    - shell
  script:
    - echo "${CI_REGISTRY_IMAGE}"
    - sudo su
    - sudo docker build --pull -t $CI_REGISTRY_IMAGE:latest docker
    - sudo docker push $CI_REGISTRY_IMAGE:latest
